name: Generate SBOM

on: workflow_dispatch

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: nginx:latest
          format: spdx-json
          output-file: sbom.json

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: sbom.json
